["Stirling Engine"]
	#Revolution period of the simulated shaft (affects only piston movement).
	"Revolution period" = 0.2
	#Radius of the simulated crank.
	"Crank radius" = 0.125
	#Length of the simulated conrod.
	"Conrod length" = 0.5

[Debug]
	#Render thruster debug overlays (plume ray, obstruction hits, damage zones).
	Thruster = false
