#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 15 15:33:13 SAST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1.zip
