	[pantographsandwires_common_config.advanced]
		#Improves targeting of blocks when the hitbox is outside the actual block area (e.g. large or diagonal hitboxes). However, this requires a bit more computing power because 9 blocks have to be checked instead of 1.
		#Default: ON
		block_selection = true
		#If enabled, world data from old versions of this mod are converted into the new format, so that blocks or their settings are preserved as far as possible. However, this feature can cause small lag spikes when converting chunks once. If the feature is deactivated, old blocks are lost.
		#Default: ON
		use_data_fixers = true
		#If enabled, wire network data from old versions of this mod is converted into the new format, so that existing wires are preserved as far as possible. If the feature is deactivated, old wire networks are lost.
		#Default: ON
		convert_wire_network = true
		#Compresses all calculated unique hash values to save memory. Compression slows down the calculation of hash values, but uses less memory. These differences are very minimal and only useful for extremely large wire networks or very limited hardware.
		#Default: OFF
		compress_hash_values = false

	[pantographsandwires_common_config.debug]
		#Prints advanced debug information in the console. This option can be disabled for normal gameplay, but it might be useful for troubleshooting.
		#Default: OFF
		advanced_logging = false
		#Prints detailed information abount converting and updating the wire graph in the console. This option can be disabled for normal gameplay, but it might be useful for troubleshooting problems with converting wire data from older versions.
		#Default: OFF
		wire_converter_logging = false
